ALTER TABLE CLIENTB2B DROP FOREIGN KEY FK_CLIENTB2B_ID
ALTER TABLE CLIENTB2C DROP FOREIGN KEY FK_CLIENTB2C_ID
ALTER TABLE CLIENTORDER DROP FOREIGN KEY FK_CLIENTORDER_CLIENTB2C_ID
ALTER TABLE ORDERITEM DROP FOREIGN KEY FK_ORDERITEM_ORDER_ID
ALTER TABLE ORDERITEM DROP FOREIGN KEY FK_ORDERITEM_stockClientB2B_id
ALTER TABLE PROMO DROP FOREIGN KEY FK_PROMO_STOCKSUPPLIER_ID
ALTER TABLE STOCKCLIENTB2B DROP FOREIGN KEY FK_STOCKCLIENTB2B_CLIENTB2B_ID
ALTER TABLE STOCKSUPPLIER DROP FOREIGN KEY FK_STOCKSUPPLIER_WINE_ID
ALTER TABLE STOCKSUPPLIER DROP FOREIGN KEY FK_STOCKSUPPLIER_SUPPLIER_ID
ALTER TABLE STOCKSUPPLIER DROP FOREIGN KEY FK_STOCKSUPPLIER_STOCKCLIENTB2B_ID
ALTER TABLE SUPPLIER DROP FOREIGN KEY FK_SUPPLIER_ID
DROP TABLE PLATFORMUSER
DROP TABLE CLIENTB2B
DROP TABLE CLIENTB2C
DROP TABLE CLIENTORDER
DROP TABLE ORDERITEM
DROP TABLE PROMO
DROP TABLE STOCKCLIENTB2B
DROP TABLE STOCKSUPPLIER
DROP TABLE SUPPLIER
DROP TABLE WINE
